Repository DDDEastMidlandsLimited/dddem-web, pull requests merged in 2019-04, with the labels that each got.

#58 Enhancement: Add Microlise logo
  data/silver.js
  static/sponsors/Microlise_800.png
Labels: In progress, enhancement

#59 Fix: Edit Microlise Description
  data/silver.js
Labels: bug

#60 E/view talks
  components/CompanyDetailsButton.js
  components/CompanyGrid.js
  components/CompanyList.js
  components/Countdown.js
  components/ExternalLink.js
  components/Footer.js
  components/Header.js
  components/Layout.js
  components/Navigation.js
  components/NotableCompanies.js
  components/PartnerWithDescription.js
  components/PartnersList.js
  components/VenueButton.js
  components/companies/Company.js
  components/companies/CompanyDetailsButton.js
  components/companies/CompanyGrid.js
  components/companies/NotableCompanies.js
  components/companies/TieredCompanies.js
  components/home/ImportantDate.js
  components/home/ImportantDatesList.js
  components/home/TicketButton.js
  components/sponsorship/Sponsor.js
  components/sponsorship/SponsorButton.js
  components/sponsorship/SponsorDescription.js
  components/sponsorship/SponsorImage.js
  components/sponsorship/SponsorsList.js
  components/talks/FilterItem.js
  components/talks/Talk.js
  components/talks/TalkFilter.js
  components/talks/TalkList.js
  components/talks/Talks.js
  data/bronze.js
  data/dates.js
  data/extraopportunities.js
  data/gold.js
  data/levels.js
  data/partners.js
  data/silver.js
  data/sponsors.js
  data/standard.js
  data/talks.js
  pages/about.js
  pages/accessibility.js
  pages/code-of-conduct.js
  pages/faq.js
  pages/index.js
  pages/notable-companies.js
  pages/sponsorship.js
  pages/talks.js
  pages/venue.js
Labels: enhancement
