Repository DDDEastMidlandsLimited/dddem-web, pull requests merged in 2019-10, with the labels that each got.

#98 Improve image alt text for a11y
  components/companies/Company.js
  package-lock.json
  pages/speakers.js
Labels: accessibility, hacktober, hacktoberfest

#95 Add tabbing behavior
  components/Header.js
  components/home/ImportantDate.js
  package-lock.json
  pages/about/about.js
  pages/about/accessibility-information.js
  pages/about/application-information.js
  pages/about/attendee-information.js
  pages/about/speaker-information.js
  pages/about/sponsor-information.js
  pages/about/ticket-information.js
  pages/about/venue.js
  pages/agenda.js
  pages/code-of-conduct.js
  pages/index.js
  pages/speakers.js
Labels: In progress, accessibility, enhancement, hacktober, hacktoberfest

#96 Enhancement: Add crew information page
  components/Navigation.js
  pages/about/crew-information.js
Labels: In progress
