Repository DDDEastMidlandsLimited/dddem-web, pull requests merged in 2022-10, with the labels that each got.

#890 Warning fixes
  components/Head.js
  components/Header.js
  components/Header.test.js
  components/companies/CompanyInfo.js
  pages/2023/sponsorship-tiers.js
  pages/_app.js
  pages/_document.js
Labels: bug

#892 Set `--maxWorkers=1` on jest tests to improve speed
  package.json
Labels: enhancement, hacktoberfest-accepted

#895 Enhancement: Add Demographics Page
  components/Navigation.js
  pages/2023/sponsor/demographic.js
  pages/2023/sponsor/demographics.js
  public/static/demographics/2019-jobs.png
  public/static/demographics/2019-level.png
  public/static/demographics/2019-topics.png
  public/static/demographics/2021-jobs.png
  public/static/demographics/2021-level.png
  public/static/demographics/2021-topics.png
Labels: hacktoberfest-accepted

#897 Compress images on PR
  .github/workflows/calibreapp-image-actions.yml
Labels: enhancement, hacktoberfest-accepted

#891 Build errors
  components/Head.js
  components/Header.js
  components/Header.test.js
  components/companies/CompanyInfo.js
  pages/2023/sponsorship-tiers.js
  pages/_app.js
  pages/_document.js
  theme/bootstrap.css
Labels: hacktoberfest-accepted

#905 Fixes Hydration issues while running in dev mode
  babel-plugin-macros.config.js
  babel.config.js
  components/Footer.js
  package-lock.json
  package.json
Labels: bug, hacktoberfest-accepted

#901 Enhancement: Add Sponsorship Tier Page
  components/Navigation.js
  pages/2023/sponsor.js
  pages/2023/sponsorship-tiers.js
  public/static/banners/sponsorship-tiers.png
  public/static/sponsorship/tiers/booth.jpg
  public/static/sponsorship/tiers/gold.jpg
  public/static/sponsorship/tiers/platinum.jpg
  styles/components/_sponsorshipTiers.scss
Labels: In progress, DO NOT MERGE, hacktoberfest-accepted
